require('dotenv').config();
const key = process.env.FIREBASE_PRIVATE_KEY || '';
console.log('Raw length:', key.length);
console.log('Includes literal \\n:', key.includes('\\n'));
console.log('Includes real newline:', key.includes('\n'));
const parsed1 = key.replace(/\\n/g, '\n');
const parsed2 = parsed1.replace(/^"|"$/g, '').trim();
console.log('After replacing \\n and quotes:');
console.log('Includes literal \\n:', parsed2.includes('\\n'));
console.log('Includes real newline:', parsed2.includes('\n'));
console.log('Starts with:', parsed2.substring(0, 30));
console.log('Ends with:', parsed2.substring(parsed2.length - 30));
